services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: redfire3012001/app:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge